name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t website-build .

    - name: Run Docker container for master branch (publish to port 82)
      if: github.ref == 'refs/heads/master'
      run: |
        # Run the Docker container and bind it to port 82
        docker run -d -p 82:80 website-build

    - name: Run Docker container for develop branch (build only, no publish)
      if: github.ref == 'refs/heads/develop'
      run: |
        # Run the Docker container for development, but don't expose it
        docker run -d website-build
