name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t website-build .
        
    - name: Run Docker container for master branch
      if: github.ref == 'refs/heads/master'
      run: |
        docker run -d -p 82:80 website-build
        
    - name: Run Docker container for develop branch
      if: github.ref == 'refs/heads/develop'
      run: |
        docker run -d -p 80:80 website-build
